### ISSUE TITLE
There seems to be a problem getting the m3u8 url

### ISSUE THREAD

**Issue by AuilaDoi** [Yooootsuba/jabledl#3]
[INFO] 2021-09-20 20:13:50
[INFO] Collecting video informations ...
Traceback (most recent call last):
  File "D:\Anaconda\anaconda\envs\Jabledownload\Scripts\jabledl-script.py", line 33, in <module>
    sys.exit(load_entry_point('jabledl==1.0.0', 'console_scripts', 'jabledl')())
  File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\jabledl.py", line 36, in main
  File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 41, in get_metadata
  File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 60, in get_m3u8_url
AttributeError: 'NoneType' object has no attribute 'group'

I don't whether it's a problem of my network or something else.

**Comment by Yooootsuba** [comment]
> [INFO] 2021-09-20 20:13:50
> [INFO] Collecting video informations ...
> Traceback (most recent call last):
> File "D:\Anaconda\anaconda\envs\Jabledownload\Scripts\jabledl-script.py", line 33, in
> sys.exit(load_entry_point('jabledl==1.0.0', 'console_scripts', 'jabledl')())
> File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\jabledl.py", line 36, in main
> File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 41, in get_metadata
> File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 60, in get_m3u8_url
> AttributeError: 'NoneType' object has no attribute 'group'
> 
> I don't whether it's a problem of my network or something else.

Did you use the code of latest commit ? I had a commit in 20 days ago.

**Comment by AuilaDoi** [comment]
> > [INFO] 2021-09-20 20:13:50
> > [INFO] Collecting video informations ...
> > Traceback (most recent call last):
> > File "D:\Anaconda\anaconda\envs\Jabledownload\Scripts\jabledl-script.py", line 33, in
> > sys.exit(load_entry_point('jabledl==1.0.0', 'console_scripts', 'jabledl')())
> > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\jabledl.py", line 36, in main
> > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 41, in get_metadata
> > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 60, in get_m3u8_url
> > AttributeError: 'NoneType' object has no attribute 'group'
> > I don't whether it's a problem of my network or something else.
> 
> Did you use the code of latest commit ? I had a commit in 20 days ago.

Yep, it's my first time to use the code today. I have used the JableTVDownload too, which seems to have the same problem getting the m3u8 url, and I have no idea with it.

**Comment by Yooootsuba** [comment]
> > > [INFO] 2021-09-20 20:13:50
> > > [INFO] Collecting video informations ...
> > > Traceback (most recent call last):
> > > File "D:\Anaconda\anaconda\envs\Jabledownload\Scripts\jabledl-script.py", line 33, in
> > > sys.exit(load_entry_point('jabledl==1.0.0', 'console_scripts', 'jabledl')())
> > > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\jabledl.py", line 36, in main
> > > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 41, in get_metadata
> > > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 60, in get_m3u8_url
> > > AttributeError: 'NoneType' object has no attribute 'group'
> > > I don't whether it's a problem of my network or something else.
> > 
> > 
> > Did you use the code of latest commit ? I had a commit in 20 days ago.
> 
> Yep, it's my first time to use the code today. I have used the JableTVDownload too, which seems to have the same problem getting the m3u8 url, and I have no idea with it.

Can you provide the url ?

Before I replied you, I selected a random url to test the downloading, so ... it worked on my machine.

**Comment by AuilaDoi** [comment]
> > > > [INFO] 2021-09-20 20:13:50
> > > > [INFO] Collecting video informations ...
> > > > Traceback (most recent call last):
> > > > File "D:\Anaconda\anaconda\envs\Jabledownload\Scripts\jabledl-script.py", line 33, in
> > > > sys.exit(load_entry_point('jabledl==1.0.0', 'console_scripts', 'jabledl')())
> > > > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\jabledl.py", line 36, in main
> > > > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 41, in get_metadata
> > > > File "D:\Anaconda\anaconda\envs\Jabledownload\lib\site-packages\jabledl-1.0.0-py3.7.egg\jabledl\video.py", line 60, in get_m3u8_url
> > > > AttributeError: 'NoneType' object has no attribute 'group'
> > > > I don't whether it's a problem of my network or something else.
> > > 
> > > 
> > > Did you use the code of latest commit ? I had a commit in 20 days ago.
> > 
> > 
> > Yep, it's my first time to use the code today. I have used the JableTVDownload too, which seems to have the same problem getting the m3u8 url, and I have no idea with it.
> 
> Can you provide the url ?
> 
> Before I replied you, I selected a random url to test the downloading, so ... it worked on my machine.

It looks like the code works well according to your reply at least. I'll quest for another reason. Thanks for your helping.

**Comment by jpluschh** [comment]
>[INFO] 2023-07-01 13:06:55
[INFO] Collecting video informations ...
Traceback (most recent call last):
  File "/home/jchh/.local/bin//jabledl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jchh/.local/pipx/venvs/jabledl/lib/python3.11/site-packages/jabledl/jabledl.py", line 36, in main
    video.get_metadata()
  File "/home/jchh/.local/pipx/venvs/jabledl/lib/python3.11/site-packages/jabledl/video.py", line 41, in get_metadata
    self.get_m3u8_url()
  File "/home/jchh/.local/pipx/venvs/jabledl/lib/python3.11/site-packages/jabledl/video.py", line 60, in get_m3u8_url
    self.m3u8_url = re.search('https://.*m3u8', self.html).group(0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>AttributeError: 'NoneType' object has no attribute 'group'

This happened a couple of times in recent months. I thought I messed up dependencies in my system.

I tried a few different URLs. The result of failing to group m3u8 URLs is the same. Does anyone have the same issue?

**Comment by hcl67** [comment]
similar issue occured, fixed by replacing requests with selenium in Video.get_metadata, check this [fork](https://github.com/hcl67/jabledl) for reference.
